### ISSUE TITLE
[question] Custom password hashing/verification

### ISSUE THREAD

**Issue by IsraelOrtuno** [adrienZ/slip#31]
Hey @adrienZ, congrats on the package, just discovered it and it's just gold.

Just like `setCreateRandomUserId` and others, would you consider making password hashing and verification functions customizable as well? This would allow an easier migration for already existing apps.

https://github.com/adrienZ/slip/blob/master/src/runtime/core/core.ts#L245-L255

Do you see any downside here?

**Comment by adrienZ** [comment]
Hi @IsraelOrtuno, I like the idea !

I plan to implement password hashing, while i'm not sure how to properly implement it yet, I fear this could complicate things a bit.

it would also mean that @node-rs/argon2 should be treated as peer dependency ?

Give me a few days to see what i can do :)

**Comment by IsraelOrtuno** [comment]
My idea was to maybe have a default method (argon) and let the user overwrite it `hash` and `verify` methods (example), so no need to support bcrypt or any other nor its dependences. In that case the lib that you mention could just stay as it's the one offered by default. What do you think?

**Comment by adrienZ** [comment]
let's wait for https://github.com/atinux/nuxt-auth-utils/issues/155 :)

**Comment by adrienZ** [comment]
just realized that argon2 does salting...

So i changed my mind and will see later with nuxt-auth-utils password methods (maybe future defaults)

@IsraelOrtuno I let you close the issue if this is good for you

**Comment by IsraelOrtuno** [comment]
This looks brilliant, thanks a lot and nice work!
